on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Prepare und Publish

jobs:
  deploy-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Run ci
        run: |
          npm ci
          npm run validate
          mv docs/README.qmd index.qmd
      -  name: Install Python and Dependencies
         uses: actions/setup-python@v4
         with:
           python-version: '3.12'
           cache: 'pip3'
      - run: pip3 install pyyaml

      - name : Execution scripts
        run: |
          python3 ./scripts/replace-language.py
          python3 ./scripts/tags-to-i18n.py
      - name : Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}